// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYcJuEvhhf2dSTMjJDnOrIFhFRS4qOdgo',
    appId: '1:642037584429:web:083349e31fe54a32109ea4',
    messagingSenderId: '642037584429',
    projectId: 'cumamesajlari-4bd11',
    authDomain: 'cumamesajlari-4bd11.firebaseapp.com',
    storageBucket: 'cumamesajlari-4bd11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXWToduKQMWkUm_hojp1QzWKDgYDjnDNk',
    appId: '1:642037584429:android:84026112052a7035109ea4',
    messagingSenderId: '642037584429',
    projectId: 'cumamesajlari-4bd11',
    storageBucket: 'cumamesajlari-4bd11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWmK2CciS3vmKdcoo5P2hKQC6DvmFIXgE',
    appId: '1:642037584429:ios:5e92a9357bf457dc109ea4',
    messagingSenderId: '642037584429',
    projectId: 'cumamesajlari-4bd11',
    storageBucket: 'cumamesajlari-4bd11.appspot.com',
    iosClientId: '642037584429-ouriqen3m2p7creulsd3l7tvdp4jglcv.apps.googleusercontent.com',
    iosBundleId: 'com.hafizramiz.cumamesajlari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWmK2CciS3vmKdcoo5P2hKQC6DvmFIXgE',
    appId: '1:642037584429:ios:5e92a9357bf457dc109ea4',
    messagingSenderId: '642037584429',
    projectId: 'cumamesajlari-4bd11',
    storageBucket: 'cumamesajlari-4bd11.appspot.com',
    iosClientId: '642037584429-ouriqen3m2p7creulsd3l7tvdp4jglcv.apps.googleusercontent.com',
    iosBundleId: 'com.hafizramiz.cumamesajlari',
  );
}
